name: tailrec
description: This package help you to convert recursive function into the while-loop codes. so that program won't meet out of memory that caused by stack overflow.
version: 1.0.1
homepage: https://github.com/anyone-developer

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
